#pragma once

#include "Definitions/Flags.h"
#include "Definitions/Input.h"
#include "Definitions/Buttons.h"
#include "Definitions/Const.h"

#include "Utilities/Virtuals.h"
#include "Utilities/CRC32.h"

#include "Structures/Color.h"
#include "Structures/Matrix.h"
#include "Structures/Vector.h"
#include "Structures/PlayerInfo.h"

#include "Classes/CShowPixelsParams.h"
#include "Classes/CUserCmd.h"
#include "Classes/CInput.h"
#include "Classes/CBaseHandle.h"
#include "Classes/CGlobalVarsBase.h"
#include "Classes/ClientClass.h"
#include "Classes/IHandleEntity.h"
#include "Classes/IClientUnknown.h"
#include "Classes/IClientRenderable.h"
#include "Classes/IClientNetworkable.h"
#include "Classes/IClientThinkable.h"
#include "Classes/ICollideable.h"
#include "Classes/IClientEntity.h"
#include "Classes/RecvTable.h"

#include "Interfaces/ICvar.h"
#include "Interfaces/IPanel.h"
#include "Interfaces/ISurface.h"
#include "Interfaces/IVModelInfo.h"
#include "Interfaces/ILauncherMgr.h"
#include "Interfaces/IInputSystem.h"
#include "Interfaces/IInputInternal.h"
#include "Interfaces/IVEngineClient.h"
#include "Interfaces/IVModelRender.h"
#include "Interfaces/IVDebugOverlay.h"
#include "Interfaces/IBaseClientDLL.h"
#include "Interfaces/IMaterialSystem.h"
#include "Interfaces/IClientEntityList.h"
#include "Interfaces/IGameEventManager2.h"